### PR TITLE
Enable SK Pro Settings tab filter for hooking in SK Pro plugin

### PR DESCRIPTION
**Pull request by lushkant**
Adds a hook for SK Pro Plugin to remove Promotional Settings Tab #[20](https://github.com/mauryaratan/style-kits-pro/issues/20)

### CODE REVIEW

**Comment by mauryaratan** [comment]
@lushkant if we must add a filter, then check for it, then we're probably doing something in Pro plugin as well?

How about we just include the Pro tab specificially when Pro plugin in installed? You could use a `class_exists` check.

**Comment by lushkant** [comment]
@mauryaratan that sounds more performant!

**Comment by lushkant** [comment]
This is a go now! :)

**Comment by mauryaratan** [comment]
This is great @lushkant, what's your thought on not including the file in first place?

**Pull request merged**
